import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { ColorInput } from '@mantine/core';


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Tabs color="red" radius="xs" orientation="horizontal">

        <Tabs.List>
          <Tabs.Tab color="yellow" value="gallery">Home</Tabs.Tab>
          <Tabs.Tab color="blue" value="accordion">Accordion</Tabs.Tab>
          <Tabs.Tab value="badges">Badges</Tabs.Tab>
          <Tabs.Tab value="card">Card</Tabs.Tab>
          <Tabs.Tab value="indicator">Indicator</Tabs.Tab>
        </Tabs.List>

        <Tabs.Panel value="gallery" pl="xs">
          Home - This is a compiliation of test mantine components
        </Tabs.Panel>

        <Tabs.Panel value="accordion" pl="xs">
          <MyAccordion />
        </Tabs.Panel>

        <Tabs.Panel value="badges" pl="xs">
          <MyBadges />
        </Tabs.Panel>

        <Tabs.Panel value="card">
          <Cardgrid />
        </Tabs.Panel>

        <Tabs.Panel value="indicator" pl="xs">
          <MyIndicator />
        </Tabs.Panel>

        </Tabs>
      </main>

    </div>
  )
}
