import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { ColorInput } from '@mantine/core';
import { Tabs } from '@mantine/core';
import MyAccordion from '../components/myaccordion';
import MyBadges from '../components/mybadges';
import MyCard from '../components/mycard';
import MyIndicator from '../components/indicator';
import Cardgrid from '../components/cardgrid';
import { Text } from '@mantine/core';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
      <Tabs inverted radius="xl" orientation="vertical" defaultValue="home">
      <div className='nav-buttons'>
        <Tabs.List>
          <Tabs.Tab value="home">Home</Tabs.Tab>
          <Tabs.Tab color="blue" value="accordion">Accordion</Tabs.Tab>
          <Tabs.Tab value="badges">Badges</Tabs.Tab>
          <Tabs.Tab value="card">Card</Tabs.Tab>
          <Tabs.Tab value="indicator">Indicator</Tabs.Tab>
        </Tabs.List>
      </div>
        
        <nav className={styles.main} >
          <Tabs.Panel value="home" pl="xs">
            <Text weight={500} size="xl">Home Testing - <a href='https://mantine.dev/pages/getting-started/' target={"_blank"}>Mantine Components</a></Text>
          </Tabs.Panel>

          <Tabs.Panel value="accordion" pl="xs">
            <Text weight={500} size="xl"><a href='https://mantine.dev/core/accordion/' target={"_blank"}>Accordion</a></Text>
            <MyAccordion />
          </Tabs.Panel>

          <Tabs.Panel value="badges" pl="xs">
            <Text weight={500} size="xl"><a href='https://mantine.dev/core/badge/' target={"_blank"}>Badges</a></Text>
            <MyBadges />
          </Tabs.Panel>

          <Tabs.Panel value="card" pl="xs">
            <Text weight={500} size="xl"><a href='https://mantine.dev/core/card/' target={"_blank"}>Card</a></Text>
            <Cardgrid />
          </Tabs.Panel>

          <Tabs.Panel value="indicator" pl="xs">
            <Text weight={500} size="xl"><a href='https://mantine.dev/core/indicator/' target={"_blank"}>Indicator</a></Text>
            <MyIndicator />
          </Tabs.Panel>
        </nav>

        </Tabs>
      </main>

    </div>
  )
}
